# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: JeremiahC27.Autotype
PackageVersion: "1.5.0"
PackageLocale: en-US
Publisher: Jeremiah-C27
PackageName: Autotype
License: MIT
ShortDescription: Type text with a countdown or custom global shortcuts
Tags:
- autotype
- keyboard
- typing
ManifestType: defaultLocale
ManifestVersion: 1.10.0
